version: '3.7'
services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      mongodb:
        condition: service_started
    networks:
      - main_network
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - main_network
networks:
  main_network:
    driver: bridge
volumes:
  mongo-data:
    driver: local